export const FETCH_<%= mutation_name_pluralized %>_START = 'FETCH_<%= mutation_name_pluralized %>_START'
export const FETCH_<%= mutation_name_pluralized %>_SUCCESS = 'FETCH_<%= mutation_name_pluralized %>_SUCCESS'
export const GET_RELATED_<%= mutation_name_pluralized %>_SUCCESS = 'GET_RELATED_<%= mutation_name_pluralized %>_SUCCESS'
export const GET_<%= mutation_name %>_START = 'GET_<%= mutation_name %>_START'
export const GET_<%= mutation_name %>_SUCCESS = 'GET_<%= mutation_name %>_SUCCESS'
export const ADD_<%= mutation_name %>_START = 'ADD_<%= mutation_name %>_START'
export const ADD_<%= mutation_name %>_SUCCESS = 'ADD_<%= mutation_name %>_SUCCESS'
export const UPDATE_<%= mutation_name %>_START = 'UPDATE_<%= mutation_name %>_START'
export const UPDATE_<%= mutation_name %>_SUCCESS = 'UPDATE_<%= mutation_name %>_SUCCESS'
export const DELETE_<%= mutation_name %>_START = 'DELETE_<%= mutation_name %>_START'
export const DELETE_<%= mutation_name %>_SUCCESS = 'DELETE_<%= mutation_name %>_SUCCESS'

export const API_REQUEST_FAIL = 'API_REQUEST_FAIL'
