export const FETCH_<%= model_name.underscore.pluralize.upcase %>_START = 'FETCH_<%= model_name.underscore.pluralize.upcase %>_START'
export const FETCH_<%= model_name.underscore.pluralize.upcase %>_SUCCESS = 'FETCH_<%= model_name.underscore.pluralize.upcase %>_SUCCESS'
export const GET_RELATED_<%= model_name.underscore.pluralize.upcase %>_SUCCESS = 'GET_RELATED_<%= model_name.underscore.pluralize.upcase %>_SUCCESS'
export const GET_<%= model_name.underscore.upcase %>_START = 'GET_<%= model_name.underscore.upcase %>_START'
export const GET_<%= model_name.underscore.upcase %>_SUCCESS = 'GET_<%= model_name.underscore.upcase %>_SUCCESS'
export const ADD_<%= model_name.underscore.upcase %>_START = 'ADD_<%= model_name.underscore.upcase %>_START'
export const ADD_<%= model_name.underscore.upcase %>_SUCCESS = 'ADD_<%= model_name.underscore.upcase %>_SUCCESS'
export const UPDATE_<%= model_name.underscore.upcase %>_START = 'UPDATE_<%= model_name.underscore.upcase %>_START'
export const UPDATE_<%= model_name.underscore.upcase %>_SUCCESS = 'UPDATE_<%= model_name.underscore.upcase %>_SUCCESS'
export const DELETE_<%= model_name.underscore.upcase %>_START = 'DELETE_<%= model_name.underscore.upcase %>_START'
export const DELETE_<%= model_name.underscore.upcase %>_SUCCESS = 'DELETE_<%= model_name.underscore.upcase %>_SUCCESS'

export const API_REQUEST_FAIL = 'API_REQUEST_FAIL'
